#cloud-config
autoinstall:
  version: 1
  locale: pt_BR.UTF-8
  keyboard:
    layout: br
  
  identity:
    hostname: BRJTNO
    username: suporte
    password: $6$v2hQvx/ec0AE3gpA$VpADlI.hi.Ban4lTTsFtqzmoC46aqplwrwW/9/6cGvrL.6G8apb/H9lX5BvzNBAHyxdzyAoStJWRH9sVDFswk0
  
  storage:
    layout:
      name: custom
    config:
      # Disco principal
      - type: disk
        id: disk-vda
        path: /dev/vda
        ptable: gpt
        wipe: superblock-recursive
      
      # Partição EFI/Boot
      - type: partition
        id: partition-efi
        device: disk-vda
        number: 1
        size: 512M
        flag: boot
        grub_device: true
      
      # Partição para criptografia
      - type: partition
        id: partition-encrypted
        device: disk-vda
        number: 2
        size: -1
      
      # Formatação EFI
      - type: format
        id: format-efi
        fstype: fat32
        volume: partition-efi
      
      # Configuração de criptografia LUKS
      - type: dm_crypt
        id: dmcrypt-root
        volume: partition-encrypted
        dm_name: ubuntu-encrypted
        key: "mudar123"
      
      # Formatação da partição criptografada
      - type: format
        id: format-root
        fstype: ext4
        volume: dmcrypt-root
      
      # Montagens
      - type: mount
        id: mount-efi
        device: format-efi
        path: /boot/efi
      
      - type: mount
        id: mount-root
        device: format-root
        path: /
  
  packages:
    - ubuntu-desktop-minimal
    - cryptsetup
  
  timezone: America/Sao_Paulo
  
  late-commands:
    - echo 'Instalação com criptografia concluída'
