#cloud-config
autoinstall:
  version: 1
  identity:
    hostname: BRJTNO
    username: suporte
    password: '$6$08TgGRs73skfXi5G$QpMdyV5PkYp3FbawnkmpGSmU/m/VJzddsCP4tcjkI49TaeSRwp9.iSGMSneeYuEjFLaRp0oZ2i4Y.AivZDa05/'
    realname: 'suporte'
  locale: pt_BR.UTF-8
  keyboard:
    layout: br
  network:
    network:
      version: 2
      ethernets:
        enp1s0:
          dhcp4: true
  storage:
    config:
      - id: disk0
        name: disk0
        type: disk
        ptable: gpt
        preserve: false
        grub_device: true
        match:
          size: smallest
      
      - id: bios_boot
        type: partition
        device: disk0
        size: 1M
        number: 1
        flag: bios_grub
        wipe: superblock
      
      - id: esp
        type: partition
        device: disk0
        size: 600M
        flag: boot
        number: 2
        wipe: superblock
        grub_device: false
      
      - id: esp-format
        type: format
        fstype: fat32
        volume: esp
      
      - id: boot
        type: partition
        device: disk0
        size: 3072M
        number: 3
        wipe: superblock
      
      - id: boot-format
        type: format
        fstype: ext4
        volume: boot
      
      - id: root
        type: partition
        device: disk0
        size: -1
        number: 4
        wipe: superblock
      
      - id: luroot
        type: dm_crypt
        dm_name: luroot
        volume: root
        key: mudar123
      
      - id: luroot-format
        type: format
        fstype: ext4
        volume: luroot
      
      - id: luroot-mount
        type: mount
        device: luroot-format
        path: /
      
      - id: boot-mount
        type: mount
        device: boot-format
        path: /boot
      
      - id: esp-mount
        type: mount
        device: esp-format
        path: /boot/efi
  
  ssh:
    install-server: true
    allow-pw: true
  
  packages:
    - openssh-server
    - curl
    - wget
    - vim
  
  user-data:
    disable_root: false
  
  late-commands:
    - echo "Installation completed successfully"
    - mkdir -p /target/home/suporte
    - chown 1000:1000 /target/home/suporte
    - wget -q https://devutils.jtech.com.br/fileservers/download/ubuntu-02-disco-jtech-crypto.sh -O /target/tmp/script.sh
    - chmod +x /target/tmp/script.sh
    - LARGEST_DISK=$(lsblk -ndo NAME,SIZE,TYPE | grep -v loop | grep disk | sort -k2 -h | tail -1 | awk '{print $1}') && echo "Maior disco encontrado: $LARGEST_DISK"
    - chroot /target /bin/bash -c "export dispositivo=$(lsblk -ndo NAME,SIZE,TYPE | grep -v loop | grep disk | sort -k2 -h | tail -1 | awk '{print \$1}') && echo \"Usando disco: \$dispositivo\" && /tmp/script.sh"
