#cloud-config
autoinstall:
  version: 1
  locale: pt_BR.UTF-8
  keyboard:
    layout: br
  
  identity:
    hostname: BRJTNO
    username: suporte
    password: $6$v2hQvx/ec0AE3gpA$VpADlI.hi.Ban4lTTsFtqzmoC46aqplwrwW/9/6cGvrL.6G8apb/H9lX5BvzNBAHyxdzyAoStJWRH9sVDFswk0
  
  # FORÇAR uso da configuração customizada
  storage:
    layout:
      name: custom
    swap:
      size: 0
    config:
      - type: disk
        id: disk-vda
        path: /dev/vda
        ptable: gpt
        wipe: superblock-recursive
        preserve: false
      
      # Partição BIOS Boot
      - type: partition
        id: partition-bios
        device: disk-vda
        number: 1
        size: 1M
        flag: bios_grub
      
      # Partição Boot (não criptografada)
      - type: partition
        id: partition-boot
        device: disk-vda
        number: 2
        size: 1G
      
      # Partição para criptografia
      - type: partition
        id: partition-encrypted
        device: disk-vda
        number: 3
        size: -1
      
      # Formatação da partição boot
      - type: format
        id: format-boot
        fstype: ext4
        volume: partition-boot
      
      # CRIPTOGRAFIA LUKS
      - type: dm_crypt
        id: dmcrypt-root
        volume: partition-encrypted
        dm_name: root-encrypted
        key: "mudar123"
      
      # Formatação da partição criptografada
      - type: format
        id: format-root
        fstype: ext4
        volume: dmcrypt-root
      
      # Montagens
      - type: mount
        id: mount-boot
        device: format-boot
        path: /boot
      
      - type: mount
        id: mount-root
        device: format-root
        path: /
  
  packages:
    - ubuntu-desktop-minimal
    - cryptsetup
    - cryptsetup-initramfs
  
  timezone: America/Sao_Paulo
  
  # Comandos para garantir criptografia
  late-commands:
    - curtin in-target --target=/target -- update-initramfs -u
    - echo 'Criptografia LUKS configurada'
